### ISSUE TITLE
During deployment, databricks URL is incorrect

### ISSUE THREAD

**Issue by tyclintw** [Azure/AI-PredictiveMaintenance#106]
This issue occurred on deployment page "Databricks authorization". The link "here" of text "If a new Databricks workspace was created by the solution, you can access it here." is broken. The URL started with "https://https" (https://https//westus2.azuredatabricks.net/aad/auth?has=&Workspace=/subscriptions/...). Once I removed the second "https//" the link worked as intended.

Additional notes: Please cleanup the text to inform the user they must first click the "here" before following the instructions. If the user doesn't click "here" first, they cannot log-in to databricks as the AD account has been properly setup yet.

**Comment by laramume** [comment]
I have fixed the Databricks URL issue and the instructions have been updated to be more clear. Thanks for your feedback.
