### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by tyclintw** [Azure/AI-PredictiveMaintenance#107]
I am unable to deploy my solution. The deployment fails on the "Resource provisioning" step with the following output:

Creating Databricks cluster and starting featurization streaming job | Failed |
Traceback (most recent call last): File "run.py", line 117, in <module>

**Comment by wdecay** [comment]
Tyler, do you know what was the commit ID of the code you deployed?
In the latest Databricks run.py, line 117 is blank, which makes me think you tried some older version.

**Comment by tyclintw** [comment]
I simply deployed whatever was available on 6/18. I dig into the databrick's jobs and it looks like a quota failure for my subscription. I'll look into cleaning up some resources.

featurization_task output:
Run result unavailable: job failed with error message
 Unexpected state for cluster (job-4-run-1):  Could not launch cluster due to cloud provider failures. azure_error_code: OperationNotAllowed, azure_error_message: Operation results in exceeding quota limits of Core. Maximum allowed: 100, Current in use: 99, Additional requested: 4. Please read more about quota increase at http://aka.ms/corequotaincrease.

**Comment by tyclintw** [comment]
Provisioning in a location that allowed for more cores completed successfully. I'm closing the issue but please be aware that this issue will re-occur for other peoples deployments and it's difficult to diagnose.
