### ISSUE TITLE
Azure Error: InvalidTemplate

### ISSUE THREAD

**Issue by girishkumarbk** [Azure/AI-PredictiveMaintenance#141]
Hi,

I see this error while deploying the solution via pdm-arm.json ARM template 

girishkb-mac-0:ARMTemplates girishkb$ az group deployment create -n example2-deployment -g example2 --template-file pdm-arm.json
Please provide string value for 'databricksWorkspaceUrl' (? for help): https://eastus2.azuredatabricks.net
Please provide string value for 'databricksToken' (? for help): dapif7xxxxxxxxxxxxxxxxxxxxxx4
Please provide string value for 'dsvmUsername' (? for help): xxxxxxxxxx
Please provide securestring value for 'dsvmPassword' (? for help): 
Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template resource 'linuxDsvmTemplate' at line '1' and column '7537' is not valid: Unable to parse language expression 'concat(variables('gitHubBaseUrl'),'src/CustomScripts/setup.sh ', concat(variables('gitHubBaseUrl'), '/binaries/Notebooks.zip ', concat(variables('gitHubBaseUrl'), '/binaries/spark-avro_2.11-4.0.0.jar')': expected token 'RightParenthesis' and actual 'EndOfData'.. Please see https://aka.ms/arm-template-expressions for usage details.'.

**Comment by laramume** [comment]
Issue resolved. Can you please try deploying it again
